def call_with_retry(func: Callable[..., Any]) -> Callable[..., Any]:
    """
    Ejecuta una funci贸n con reintentos en caso de errores como RateLimitError.

    Parameters
    ----------
    func : Callable
        La funci贸n que se desea ejecutar con l贸gica de reintentos.

    Returns
    -------
    Callable
        La funci贸n envuelta que incluye reintentos.
    """
    ...
